const ProjectsData = [
  {
    id: 1,
    logo: "/square.png",
    title: "Grafiti House",
    location: "JAKARTA, INDONESIA",
    category: "PRIVATE",
    tag: ["ALL", "PRIVATE"], 
    details: [
      { image: "/grafitti/01.jpg", description: "Hunian private bernuansa modern minimalis." },
      { image: "/grafitti/02.jpg", description: "Interior rumah dengan pencahayaan natural." },
      { image: "/grafitti/03.jpg", description: "" },
      { image: "/grafitti/4.jpg", description: "" },
      { image: "/grafitti/5.jpg", description: "" },
    ],
    map: { lat: -6.2088, lng: 106.8456 },
  },
  {
    id: 2,
    logo: "/square.png",
    title: "Chiganoz Barbershop",
    location: "BALI, INDONESIA",
    category: "INTERIOR",
    tag: ["ALL", "INTERIOR"], 
    details: [
      { image: "/chiganoz/chiganoz5.JPG", description: "Desain interior barbershop modern industrial." },
      { image: "/chiganoz/chiganoz2.jpg", description: "Penggunaan material kayu dan metal." },
      { image: "/chiganoz/chiganoz4.JPG" },
      { image: "/chiganoz/chiganoz3.jpg" },
      { image: "/chiganoz/chiganoz1.jpg", description: "Penggunaan material kayu dan metal." },
    ],
    map: { lat: -8.4095, lng: 115.1889 },
  },
  {
    id: 3,
    logo: "/square.png",
    title: "Pelindo Lobby Render",
    location: "SURABAYA, INDONESIA",
    category: "RENDER",
    tag: ["ALL", "RENDER"], 
    details: [
      { image: "/pelindo/4.JPG", description: "Render visual lobby utama." },
      { image: "/pelindo/2.JPG", description: "Desain area penerimaan tamu modern." },
      { image: "/pelindo/3.JPG", description: "" },
      { image: "/pelindo/1.jpg", description: "" },
      { image: "/pelindo/5.JPG", description: "" },
    ],
    map: { lat: -7.2575, lng: 112.7521 },
  },
  {
    id: 4,
    logo: "/square.png",
    title: "Taman ITS",
    location: "SURABAYA, INDONESIA",
    category: "PUBLIC",
    tag: ["ALL", "PUBLIC"], 
    details: [
      { image: "/tamanits/1.jpg", description: "Ruang publik dan area hijau kampus ITS." },
      { image: "/tamanits/2.JPG", description: "Tempat interaksi mahasiswa di luar ruangan." },
      { image: "/tamanits/3.JPG", description: "Ruang publik dan area hijau kampus ITS." },
      { image: "/tamanits/4.JPG", description: "Tempat interaksi mahasiswa di luar ruangan." },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
  {
    id: 5,
    logo: "/square.png",
    title: "Satu Atap",
    location: "BALI, INDONESIA",
    category: "CONCEPTUALS",
    tag: ["ALL", "CONCEPTUALS"], 
    details: [
      { image: "/satuatap/1.PNG", description: "Konsep hunian bersama dengan ruang komunal." },
      { image: "/satuatap/2.JPG", description: "Fasilitas bersama untuk interaksi penghuni." },
      { image: "/satuatap/3.JPG", description: "" },
      { image: "/satuatap/4.JPG", description: "" },
      { image: "/satuatap/5.JPG", description: "" },
      { image: "/satuatap/6.JPG", description: "" },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
];

export default ProjectsData;
