const ProjectsData = [
  {
    id: 1,
    logo: "/square.png",
    title: "Grafiti House",
    location: "JAKARTA, INDONESIA",
    category: "PRIVATE",
    tag: ["ALL", "PRIVATE"], 
    details: [
      { image: "/grafitti/01.jpg", description: "Hunian private bernuansa modern minimalis dengan fasad grafiti yang unik, menghadirkan kesan artistik dan personal." },
      { image: "/grafitti/02.jpg", description: "Interior rumah menampilkan pencahayaan natural melalui jendela besar dan skylight, menciptakan ruang yang terang dan nyaman." },
      { image: "/grafitti/03.jpg", description: "Ruang keluarga dirancang dengan furniture minimalis dan aksen warna netral untuk suasana hangat dan fungsional." },
      { image: "/grafitti/4.png", description: "Kamar tidur utama dilengkapi dengan akses cahaya alami dan ventilasi optimal untuk kenyamanan penghuni." },
      { image: "/grafitti/5.png", description: "Area outdoor menghadirkan taman kecil dengan tanaman hijau dan area relaksasi untuk kegiatan keluarga." },
    ],
    map: { lat: -6.2088, lng: 106.8456 },
  },
  {
    id: 2,
    logo: "/square.png",
    title: "Chiganoz Barbershop",
    location: "BALI, INDONESIA",
    category: "INTERIOR",
    tag: ["ALL", "INTERIOR"], 
    details: [
      { image: "/chiganoz/chiganoz5.jpg", description: "Desain interior barbershop modern industrial dengan kombinasi kayu dan logam." },
      { image: "/chiganoz/chiganoz2.jpg", description: "Area potong rambut dengan pencahayaan LED dan cermin besar, menciptakan pengalaman pelanggan yang nyaman." },
      { image: "/chiganoz/chiganoz4.jpg", description: "Ruang tunggu dilengkapi sofa kulit, rak majalah, dan dekorasi urban yang menarik." },
      { image: "/chiganoz/chiganoz3.jpg", description: "Dinding aksen grafiti menambahkan sentuhan artistik yang khas untuk brand Chiganoz." },
      { image: "/chiganoz/chiganoz1.jpg", description: "Material kayu dan metal dipadukan untuk memperkuat konsep industrial modern di seluruh interior." },
    ],
    map: { lat: -8.4095, lng: 115.1889 },
  },
  {
    id: 3,
    logo: "/square.png",
    title: "Pelindo Lobby Render",
    location: "SURABAYA, INDONESIA",
    category: "RENDER",
    tag: ["ALL", "RENDER"], 
    details: [
      { image: "/pelindo/4.jpg", description: "Render visual lobby utama Pelindo dengan desain modern dan material premium." },
      { image: "/pelindo/2.jpg", description: "Area penerimaan tamu yang luas dengan pencahayaan alami melalui jendela besar dan aksen dekoratif minimalis." },
      { image: "/pelindo/3.jpg", description: "Ruang tunggu elegan dilengkapi kursi modern, meja kopi, dan tanaman indoor untuk kenyamanan tamu." },
      { image: "/pelindo/1.jpg", description: "Desain interior lobby mengutamakan sirkulasi ruang yang efisien dan estetika profesional." },
      { image: "/pelindo/5.jpg", description: "Detail finishing material seperti marmer dan kayu memberikan kesan mewah dan modern." },
    ],
    map: { lat: -7.2575, lng: 112.7521 },
  },
  {
    id: 4,
    logo: "/square.png",
    title: "Taman ITS",
    location: "SURABAYA, INDONESIA",
    category: "PUBLIC",
    tag: ["ALL", "PUBLIC"], 
    details: [
      { image: "/tamanits/1.jpg", description: "Ruang publik dan area hijau kampus ITS yang dirancang untuk interaksi mahasiswa." },
      { image: "/tamanits/2.jpg", description: "Pathway taman dilengkapi pencahayaan dan seating area untuk bersantai." },
      { image: "/tamanits/3.jpg", description: "Area taman menampilkan kombinasi tanaman lokal dan fitur air yang menenangkan." },
      { image: "/tamanits/4.jpg", description: "Ruang publik multifungsi untuk kegiatan outdoor, termasuk olahraga dan berkumpul." },
      { image: "/tamanits/5.jpg", description: "Landscape didesain dengan konsep berkelanjutan dan estetika modern." },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
  {
    id: 5,
    logo: "/square.png",
    title: "Satu Atap",
    location: "BALI, INDONESIA",
    category: "CONCEPTUALS",
    tag: ["ALL", "CONCEPTUALS"], 
    details: [
      { image: "/satuatap/1.png", description: "Konsep hunian bersama dengan ruang komunal yang mendukung interaksi penghuni." },
      { image: "/satuatap/2.jpg", description: "Fasilitas bersama termasuk dapur, ruang makan, dan area lounge untuk kegiatan sosial." },
      { image: "/satuatap/3.jpg", description: "Kamar tidur dan area privasi tetap terjaga dengan desain partisi yang efisien." },
      { image: "/satuatap/4.jpg", description: "Rooftop dan teras hijau menghadirkan area outdoor yang nyaman untuk bersantai." },
      { image: "/satuatap/5.jpg", description: "Detail interior menekankan material alami dan pencahayaan optimal." },
      { image: "/satuatap/6.jpg", description: "Desain keseluruhan mengutamakan kenyamanan, estetika, dan fungsi komunitas." },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
];

export default ProjectsData;
