const ProjectsData = [
  {
    id: 1,
    logo: "/square.png",
    title: "Grafiti House",
    location: "JAKARTA, INDONESIA",
    category: "PRIVATE",
    tag: ["ALL", "PRIVATE"], 
    details: [
      { image: "/GrafiItti/01.jpg", description: "Hunian private bernuansa modern minimalis." },
      { image: "/GrafiItti/02.jpg", description: "Interior rumah dengan pencahayaan natural." },
      { image: "/GrafiItti/03.jpg", description: "" },
      { image: "/GrafiItti/4.jpg", description: "" },
      { image: "/GrafiItti/5.jpg", description: "" },
    ],
    map: { lat: -6.2088, lng: 106.8456 },
  },
  {
    id: 2,
    logo: "/square.png",
    title: "Chiganoz Barbershop",
    location: "BALI, INDONESIA",
    category: "INTERIOR",
    tag: ["ALL", "INTERIOR"], 
    details: [
      { image: "/Chiganoz/chiganoz5.jpg", description: "Desain interior barbershop modern industrial." },
      { image: "/Chiganoz/chiganoz2.jpg", description: "Penggunaan material kayu dan metal." },
      { image: "/Chiganoz/chiganoz4.jpg" },
      { image: "/Chiganoz/chiganoz3.jpg" },
      { image: "/Chiganoz/chiganoz1.jpg", description: "Penggunaan material kayu dan metal." },
    ],
    map: { lat: -8.4095, lng: 115.1889 },
  },
  {
    id: 3,
    logo: "/square.png",
    title: "Pelindo Lobby Render",
    location: "SURABAYA, INDONESIA",
    category: "RENDER",
    tag: ["ALL", "RENDER"], 
    details: [
      { image: "/Pelindo/4.jpg", description: "Render visual lobby utama." },
      { image: "/Pelindo/2.jpg", description: "Desain area penerimaan tamu modern." },
      { image: "/Pelindo/3.jpg", description: "" },
      { image: "/Pelindo/1.jpg", description: "" },
      { image: "/Pelindo/5.jpg", description: "" },
    ],
    map: { lat: -7.2575, lng: 112.7521 },
  },
  {
    id: 4,
    logo: "/square.png",
    title: "Taman ITS",
    location: "SURABAYA, INDONESIA",
    category: "PUBLIC",
    tag: ["ALL", "PUBLIC"], 
    details: [
      { image: "/TAMANITS/1.jpg", description: "Ruang publik dan area hijau kampus ITS." },
      { image: "/TAMANITS/2.jpg", description: "Tempat interaksi mahasiswa di luar ruangan." },
      { image: "/TAMANITS/3.jpg", description: "Ruang publik dan area hijau kampus ITS." },
      { image: "/TAMANITS/4.jpg", description: "Tempat interaksi mahasiswa di luar ruangan." },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
  {
    id: 5,
    logo: "/square.png",
    title: "Satu Atap",
    location: "BALI, INDONESIA",
    category: "CONCEPTUALS",
    tag: ["ALL", "CONCEPTUALS"], 
    details: [
      { image: "/SatuAtap/1.png", description: "Konsep hunian bersama dengan ruang komunal." },
      { image: "/SatuAtap/2.jpg", description: "Fasilitas bersama untuk interaksi penghuni." },
      { image: "/SatuAtap/3.jpg", description: "" },
      { image: "/SatuAtap/4.jpg", description: "" },
      { image: "/SatuAtap/5.jpg", description: "" },
      { image: "/SatuAtap/6.jpg", description: "" },
    ],
    map: { lat: -7.2825, lng: 112.7954 },
  },
];

export default ProjectsData;
